/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package entornos.tonyin;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class HotelTest {
    @Test
    public void testRegistrarUsuario() {
        App.Hotel hotel = new App().new Hotel();
        hotel.registrarUsuario("usuario1", "usuario1@email.com");
        hotel.registrarUsuario("usuario2", "usuario2@email.com");
        hotel.registrarUsuario("usuario3", "usuario3@email.com");
        hotel.registrarUsuario("usuario4", "usuario4@email.com");
        assertEquals(4, hotel.getUsuarios().size());
    }

    @Test
    public void testEliminarUsuario() {
        App.Hotel hotel = new App().new Hotel();
        hotel.registrarUsuario("usuario1", "usuario1@email.com");
        hotel.registrarUsuario("usuario2", null);
        hotel.registrarUsuario("usuario3", null);
        hotel.registrarUsuario("usuario4", "usuario4@email.com");
        hotel.eliminarUsuario("usuario1");
        hotel.eliminarUsuario("usuario2");
        assertEquals(2, hotel.getUsuarios().size());
    }

    @Test
    public void testRegistrarHabitacion() {
        App.Hotel hotel = new App().new Hotel();
        hotel.registrarHabitacion(101, "simple", 50.0);
        hotel.registrarHabitacion(150, "VIP", 150.0);
        hotel.registrarHabitacion(169, "Presidencial", 200.0);
        assertEquals(3, hotel.listarHabitaciones().size());
    }

    @Test
    public void testEliminarHabitacion() {
        App.Hotel hotel = new App().new Hotel();
        hotel.registrarHabitacion(101, "simple", 50.0);
        hotel.registrarHabitacion(150, "VIP", 150.0);
        hotel.registrarHabitacion(169, "Presidencial", 200.0);
        hotel.eliminarHabitacion(101);
        assertEquals(2, hotel.listarHabitaciones().size());
    }

    @Test
    public void testListarHabitaciones() {
        App.Hotel hotel = new App().new Hotel();
        hotel.registrarHabitacion(101, "simple", 50.0);
        hotel.registrarHabitacion(150, "VIP", 150.0);
        hotel.registrarHabitacion(169, "Presidencial", 200.0);
        assertEquals(3, hotel.listarHabitaciones().size());
    }

    @Test
    public void testHacerReserva() {
        App.Hotel hotel = new App().new Hotel();
        App.Usuario usuario1 = new App().new Usuario("usuario1", "usuario1@email.com");
        App.Usuario usuario3 = new App().new Usuario("usuario3", null);
        hotel.registrarUsuario(usuario1.getNombreUsuario(), usuario1.getCorreoElectronico());
        hotel.registrarUsuario(usuario3.getNombreUsuario(), null);
        hotel.registrarHabitacion(101, "simple", 50.0);
        hotel.registrarHabitacion(169, "Presidencial", 200.0);
        hotel.hacerReserva(101, usuario1);
        hotel.hacerReserva(169, usuario3);
    }
    @Test
    public void testVisualizarReservas() {
        App.Hotel hotel = new App().new Hotel();
        App.Usuario usuario1 = new App().new Usuario("usuario1", "usuario1@email.com");
        hotel.registrarUsuario(usuario1.getNombreUsuario(), usuario1.getCorreoElectronico());
        hotel.registrarHabitacion(101, "simple", 50.0);
        hotel.hacerReserva(101, usuario1);
        assertEquals(1, hotel.visualizarReservas("usuario1").size());
    }
}
